version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/client"
   schedule:
      interval: "weekly"
      day: "friday"
      time: "20:00"
      timezone: "Asia/Dhaka"
    open-pull-requests-limit: 5
      
  - package-ecosystem: "npm" 
    directory: "/server"
   schedule:
      interval: "weekly"
      day: "friday"
      time: "20:00"
      timezone: "Asia/Dhaka"
    open-pull-requests-limit: 5
